export type Scene = {
	id: string
	title: string
	location: string
	level: string
	objective: string
	narrative: string
	progressLabel: string
	imageUrl: string
	photoCredit: string
	photoUrl: string
	accent: string
	actions: string[]
}

export type ExerciseType = 'chunk' | 'sentence' | 'transform' | 'scene'
export type SprintPhase = 'warmup' | 'produce' | 'repair' | 'speak'
export type CurriculumStrand =
	| 'input'
	| 'output'
	| 'language-focus'
	| 'fluency'
export type RoundFocus =
	| 'core'
	| 'verbs-frames'
	| 'past-pronouns'
	| 'topics'
	| 'stretch'

export type Exercise = {
	id: string
	type: ExerciseType
	sceneId: string
	promptEnglish: string
	targetItalian: string
	acceptedItalian: string[]
	hints: string[]
	tags: string[]
	phraseFamily: string
	difficulty: 1 | 2 | 3
	phase?: SprintPhase
	action?: string
	communicativeGoal?: string
	spokenCue?: string
	repairPrompts?: string[]
	sourceId?: string
	curriculumWeeks?: [number, number]
	strand?: CurriculumStrand
	roundFocus?: RoundFocus
	keyVerb?: string
	construction?: string
	npcLine?: string
}

export type SceneVocabulary = {
	id: string
	sceneId: string
	italian: string
	english: string
	partOfSpeech: string
}

const unsplash = (photoId: string) =>
	`https://images.unsplash.com/${photoId}?auto=format&fit=crop&w=1600&q=80`

export const sprintPhaseOrder: SprintPhase[] = [
	'warmup',
	'produce',
	'repair',
	'speak',
]

export const sprintPhaseLabels: Record<SprintPhase, string> = {
	warmup: 'Warm phrase',
	produce: 'Build fast',
	repair: 'Repair',
	speak: 'Say aloud',
}

const actionByPhraseFamily: Record<string, string> = {
	'Giving opinions': 'Ask opinion',
	'Asking follow-up questions': 'Ask follow-up',
	Softening: 'Disagree softly',
	'Offering help': 'Offer help',
	'Telling past events': 'Tell a story',
	'Asking advice': 'Ask advice',
	'Describing taste': 'Describe taste',
	'Summarising news': 'Summarise',
	'Conversation repair': 'Repeat',
	'Confirming details': 'Confirm',
	'Making plans': 'Plan next time',
	Comparing: 'Compare',
	Reacting: 'React',
	Inviting: 'Invite',
}

export const scenes: Scene[] = [
	{
		id: 'milan-cafe',
		title: 'Milan Cafe',
		location: 'Brera, Milan',
		level: 'A2 -> B1',
		objective: 'Open a relaxed conversation and ask for an opinion.',
		narrative:
			'You meet a friend outside a busy cafe. The aim is to sound natural, curious, and unhurried.',
		progressLabel: 'Scene beat 1 of 4',
		imageUrl: unsplash('photo-1631351856433-ab4389985628'),
		photoCredit: 'Wouter Groote Veldman on Unsplash',
		photoUrl:
			'https://unsplash.com/photos/brown-wicker-chairs-and-table-on-street-during-daytime-Q3hXRT95rCY',
		accent: '#ffb703',
		actions: ['Greet', 'Ask opinion', 'React', 'Continue chat'],
	},
	{
		id: 'family-table',
		title: 'Family Table',
		location: 'Dinner with friends',
		level: 'A2 -> B1',
		objective: 'Talk about family, plans, and what happened recently.',
		narrative:
			'The table is lively. You need short, warm sentences that keep the conversation moving.',
		progressLabel: 'Scene beat 1 of 4',
		imageUrl: unsplash('photo-1658951863101-b2fbab790b39'),
		photoCredit: 'Jay Gajjar on Unsplash',
		photoUrl:
			'https://unsplash.com/it/foto/persone-che-mangiano-la-pizza-a-un-tavolo-Cu4KmBDvclQ',
		accent: '#fb6f92',
		actions: ['Offer help', 'Tell a story', 'Ask follow-up', 'Compare tastes'],
	},
	{
		id: 'bookshop',
		title: 'Bookshop',
		location: 'Independent bookshop',
		level: 'B1 bridge',
		objective: 'Ask for recommendations and explain cultural preferences.',
		narrative:
			'You are browsing with someone who knows Italian books and films. Be specific, but keep it simple.',
		progressLabel: 'Locked after cafe beat 2',
		imageUrl: unsplash('photo-1762350834823-8b8cab219191'),
		photoCredit: 'Junaid Rahim on Unsplash',
		photoUrl:
			'https://unsplash.com/photos/interior-of-a-modern-bookstore-with-arched-shelves-ygsCgba7ptc',
		accent: '#2ec4b6',
		actions: ['Ask advice', 'Describe taste', 'Compare', 'Recommend back'],
	},
	{
		id: 'piazza-newsstand',
		title: 'Piazza Newsstand',
		location: 'Piazza del Duomo',
		level: 'B1 bridge',
		objective: 'Turn a headline into a simple opinion and a follow-up question.',
		narrative:
			'You notice a headline and use it as a low-pressure way into culture and news chat.',
		progressLabel: 'Locked after bookshop beat 1',
		imageUrl: unsplash('photo-1766475341256-689f4f6ef4cf'),
		photoCredit: 'Paulo De Jesus on Unsplash',
		photoUrl:
			'https://unsplash.com/photos/milan-cathedral-and-piazza-del-duomo-with-people-v_nRFtoUWdk',
		accent: '#3a86ff',
		actions: ['Read headline', 'Summarise', 'Ask view', 'Disagree softly'],
	},
	{
		id: 'station',
		title: 'Railway Platform',
		location: 'Italian station',
		level: 'A2 repair',
		objective: 'Ask for details, confirm, and repair misunderstanding.',
		narrative:
			'The station is noisy. Practise short sentences that help you stay calm and clear.',
		progressLabel: 'Available as repair scene',
		imageUrl: unsplash('photo-1767725162026-f2195e9b1dd0'),
		photoCredit: 'Tim Photoguy on Unsplash',
		photoUrl:
			'https://unsplash.com/photos/train-at-a-station-platform-with-exit-sign-IOQXzwdAowE',
		accent: '#8338ec',
		actions: ['Ask', 'Confirm', 'Repeat', 'Solve'],
	},
	{
		id: 'cinema',
		title: 'Cinema Foyer',
		location: 'Florence cinema',
		level: 'B1 bridge',
		objective: 'Discuss a film and explain what you liked or found slow.',
		narrative:
			'After the film, you need opinions, reasons, and gentle disagreement.',
		progressLabel: 'Locked after culture streak',
		imageUrl: unsplash('photo-1698213297907-d432ed91315f'),
		photoCredit: 'David Mkrtchian on Unsplash',
		photoUrl:
			'https://unsplash.com/photos/a-sign-that-reads-cinema-above-a-doorway-WU7MyD4nX-M',
		accent: '#ff006e',
		actions: ['Invite', 'React', 'Explain why', 'Plan next time'],
	},
]

export const exercises: Exercise[] = [
	{
		id: 'cafe-opinion-1',
		type: 'scene',
		sceneId: 'milan-cafe',
		promptEnglish: 'In my opinion, the coffee here is very good.',
		targetItalian: 'Secondo me, il caffe qui e molto buono.',
		acceptedItalian: [
			'secondo me il caffe qui e molto buono',
			'secondo me il cafe qui e molto buono',
			'secondo me il caffè qui è molto buono',
		],
		hints: ['Start with "Secondo me".', 'Use "qui" for "here".'],
		tags: ['opinion', 'accent', 'article'],
		phraseFamily: 'Giving opinions',
		difficulty: 1,
		npcLine: 'Cominciamo con una frase semplice.',
	},
	{
		id: 'cafe-followup-1',
		type: 'sentence',
		sceneId: 'milan-cafe',
		promptEnglish: 'What do you think about this place?',
		targetItalian: 'Che cosa pensi di questo posto?',
		acceptedItalian: [
			'che cosa pensi di questo posto',
			'cosa pensi di questo posto',
			'che ne pensi di questo posto',
		],
		hints: ['"What do you think" can be "Che cosa pensi".'],
		tags: ['question', 'preposition'],
		phraseFamily: 'Asking follow-up questions',
		difficulty: 1,
	},
	{
		id: 'cafe-soften-1',
		type: 'chunk',
		sceneId: 'milan-cafe',
		promptEnglish: 'I am not sure, but it seems interesting.',
		targetItalian: 'Non sono sicuro, ma mi sembra interessante.',
		acceptedItalian: [
			'non sono sicuro ma mi sembra interessante',
			'non sono sicura ma mi sembra interessante',
		],
		hints: ['Use "mi sembra" for "it seems to me".'],
		tags: ['softening', 'gender'],
		phraseFamily: 'Softening',
		difficulty: 2,
	},
	{
		id: 'family-week-1',
		type: 'sentence',
		sceneId: 'family-table',
		promptEnglish: 'How was your week?',
		targetItalian: 'Com e stata la tua settimana?',
		acceptedItalian: [
			'com e stata la tua settimana',
			'com è stata la tua settimana',
			'come e stata la tua settimana',
			'come è stata la tua settimana',
		],
		hints: ['Use "stata" because "settimana" is feminine.'],
		tags: ['question', 'agreement', 'past'],
		phraseFamily: 'Asking follow-up questions',
		difficulty: 1,
		npcLine: 'A tavola, una buona domanda apre tutto.',
	},
	{
		id: 'family-story-1',
		type: 'transform',
		sceneId: 'family-table',
		promptEnglish: 'Yesterday we went to the cinema, but the film was too long.',
		targetItalian: 'Ieri siamo andati al cinema, ma il film era troppo lungo.',
		acceptedItalian: [
			'ieri siamo andati al cinema ma il film era troppo lungo',
			'ieri siamo andate al cinema ma il film era troppo lungo',
		],
		hints: ['Movement verb: "siamo andati".', 'Use "era" for description in the past.'],
		tags: ['past', 'auxiliary', 'imperfect'],
		phraseFamily: 'Telling past events',
		difficulty: 3,
	},
	{
		id: 'family-help-1',
		type: 'sentence',
		sceneId: 'family-table',
		promptEnglish: 'Can I help you with dinner?',
		targetItalian: 'Posso aiutarti con la cena?',
		acceptedItalian: [
			'posso aiutarti con la cena',
			'posso aiutare con la cena',
			'ti posso aiutare con la cena',
		],
		hints: ['"Help you" can be "aiutarti".'],
		tags: ['clitic', 'question'],
		phraseFamily: 'Offering help',
		difficulty: 1,
	},
	{
		id: 'bookshop-rec-1',
		type: 'scene',
		sceneId: 'bookshop',
		promptEnglish: 'Can you recommend a contemporary Italian novel?',
		targetItalian: 'Mi puo consigliare un romanzo italiano contemporaneo?',
		acceptedItalian: [
			'mi puo consigliare un romanzo italiano contemporaneo',
			'mi può consigliare un romanzo italiano contemporaneo',
			'puoi consigliarmi un romanzo italiano contemporaneo',
		],
		hints: ['Formal: "Mi puo consigliare".', 'Informal: "Puoi consigliarmi".'],
		tags: ['politeness', 'clitic', 'culture'],
		phraseFamily: 'Asking advice',
		difficulty: 2,
	},
	{
		id: 'bookshop-taste-1',
		type: 'sentence',
		sceneId: 'bookshop',
		promptEnglish: 'I like stories about families and cities.',
		targetItalian: 'Mi piacciono le storie sulle famiglie e sulle citta.',
		acceptedItalian: [
			'mi piacciono le storie sulle famiglie e sulle citta',
			'mi piacciono le storie sulle famiglie e sulle città',
		],
		hints: ['Plural thing liked: "mi piacciono".'],
		tags: ['plural', 'preposition', 'culture'],
		phraseFamily: 'Describing taste',
		difficulty: 2,
	},
	{
		id: 'news-headline-1',
		type: 'scene',
		sceneId: 'piazza-newsstand',
		promptEnglish: 'I read that there is an important exhibition in Milan.',
		targetItalian: 'Ho letto che c e una mostra importante a Milano.',
		acceptedItalian: [
			'ho letto che c e una mostra importante a milano',
			'ho letto che cè una mostra importante a milano',
			'ho letto che c e una mostra importante in milano',
			'ho letto che c e un importante mostra a milano',
			'ho letto che c è una mostra importante a milano',
		],
		hints: ['Use "Ho letto che..." for "I read that...".'],
		tags: ['news', 'article', 'word-order'],
		phraseFamily: 'Summarising news',
		difficulty: 2,
	},
	{
		id: 'news-opinion-1',
		type: 'sentence',
		sceneId: 'piazza-newsstand',
		promptEnglish: 'It seems interesting, but I do not know much about it.',
		targetItalian: 'Mi sembra interessante, ma non ne so molto.',
		acceptedItalian: [
			'mi sembra interessante ma non ne so molto',
			'sembra interessante ma non ne so molto',
		],
		hints: ['"About it" can be "ne" in this phrase.'],
		tags: ['pronoun', 'softening', 'news'],
		phraseFamily: 'Softening',
		difficulty: 3,
	},
	{
		id: 'station-repeat-1',
		type: 'chunk',
		sceneId: 'station',
		promptEnglish: 'Sorry, could you repeat that more slowly?',
		targetItalian: 'Scusi, puo ripetere piu lentamente?',
		acceptedItalian: [
			'scusi puo ripetere piu lentamente',
			'scusi può ripetere più lentamente',
			'scusa puoi ripetere piu lentamente',
		],
		hints: ['Formal: "Scusi, puo..."', 'Informal: "Scusa, puoi..."'],
		tags: ['repair', 'politeness'],
		phraseFamily: 'Conversation repair',
		difficulty: 1,
	},
	{
		id: 'station-confirm-1',
		type: 'sentence',
		sceneId: 'station',
		promptEnglish: 'So the train leaves from platform seven?',
		targetItalian: 'Quindi il treno parte dal binario sette?',
		acceptedItalian: [
			'quindi il treno parte dal binario sette',
			'allora il treno parte dal binario sette',
		],
		hints: ['"Platform" is "binario" for trains.'],
		tags: ['travel', 'preposition'],
		phraseFamily: 'Confirming details',
		difficulty: 1,
	},
	{
		id: 'cinema-react-1',
		type: 'scene',
		sceneId: 'cinema',
		promptEnglish: 'I liked the film, even though it was a bit slow.',
		targetItalian: 'Mi e piaciuto il film, anche se era un po lento.',
		acceptedItalian: [
			'mi e piaciuto il film anche se era un po lento',
			'mi è piaciuto il film anche se era un po lento',
			'mi è piaciuto il film anche se era un po lento',
			'mi e piaciuto il film anche se era un po lento',
		],
		hints: ['For liking a film: "mi e piaciuto il film".'],
		tags: ['past', 'opinion', 'imperfect'],
		phraseFamily: 'Giving opinions',
		difficulty: 3,
	},
	{
		id: 'cinema-plan-1',
		type: 'sentence',
		sceneId: 'cinema',
		promptEnglish: 'Next time we could see something lighter.',
		targetItalian: 'La prossima volta potremmo vedere qualcosa di piu leggero.',
		acceptedItalian: [
			'la prossima volta potremmo vedere qualcosa di piu leggero',
			'la prossima volta potremmo vedere qualcosa di più leggero',
		],
		hints: ['"We could" is "potremmo".'],
		tags: ['conditional', 'planning'],
		phraseFamily: 'Making plans',
		difficulty: 3,
	},
	{
		id: 'cafe-warm-secondo-me',
		type: 'chunk',
		sceneId: 'milan-cafe',
		phase: 'warmup',
		action: 'Ask opinion',
		promptEnglish: 'In my opinion...',
		targetItalian: 'Secondo me...',
		acceptedItalian: ['secondo me'],
		hints: ['This is a reusable opinion opener.'],
		tags: ['opinion', 'chunk'],
		phraseFamily: 'Giving opinions',
		difficulty: 1,
		communicativeGoal: 'Open an opinion quickly.',
		spokenCue: 'Say it once aloud before typing.',
		repairPrompts: ['Now say: In my opinion, it is useful.'],
	},
	{
		id: 'cafe-produce-fast-1',
		type: 'sentence',
		sceneId: 'milan-cafe',
		phase: 'produce',
		action: 'Ask opinion',
		promptEnglish: 'In my opinion, this place is welcoming.',
		targetItalian: 'Secondo me, questo posto e accogliente.',
		acceptedItalian: [
			'secondo me questo posto e accogliente',
			'secondo me questo posto è accogliente',
		],
		hints: ['Keep "questo posto" together.'],
		tags: ['opinion', 'adjective'],
		phraseFamily: 'Giving opinions',
		difficulty: 1,
		communicativeGoal: 'Give a short opinion without waiting for perfection.',
		spokenCue: 'Say it in under eight seconds, then type it.',
		repairPrompts: ['Swap the adjective: This place is interesting.'],
	},
	{
		id: 'cafe-speak-followup-1',
		type: 'scene',
		sceneId: 'milan-cafe',
		phase: 'speak',
		action: 'Continue chat',
		promptEnglish: 'Ask a follow-up: Do you often come here?',
		targetItalian: 'Vieni spesso qui?',
		acceptedItalian: ['vieni spesso qui', 'venite spesso qui'],
		hints: ['"Often" is "spesso".'],
		tags: ['question', 'frequency'],
		phraseFamily: 'Asking follow-up questions',
		difficulty: 1,
		communicativeGoal: 'Keep a conversation moving with one simple question.',
		spokenCue: 'Say it aloud as if the person is across the table.',
		repairPrompts: ['Now ask: Do you like this place?'],
	},
	{
		id: 'family-warm-help',
		type: 'chunk',
		sceneId: 'family-table',
		phase: 'warmup',
		action: 'Offer help',
		promptEnglish: 'Can I help you?',
		targetItalian: 'Posso aiutarti?',
		acceptedItalian: ['posso aiutarti', 'ti posso aiutare', 'posso aiutare'],
		hints: ['"Aiutarti" means "help you".'],
		tags: ['clitic', 'question'],
		phraseFamily: 'Offering help',
		difficulty: 1,
		communicativeGoal: 'Offer help naturally.',
		spokenCue: 'Say it warmly, not perfectly.',
		repairPrompts: ['Add context: Can I help you with dinner?'],
	},
	{
		id: 'family-produce-plans-1',
		type: 'sentence',
		sceneId: 'family-table',
		phase: 'produce',
		action: 'Ask follow-up',
		promptEnglish: 'What are you doing this weekend?',
		targetItalian: 'Che cosa fai questo fine settimana?',
		acceptedItalian: [
			'che cosa fai questo fine settimana',
			'cosa fai questo fine settimana',
			'che fai questo fine settimana',
		],
		hints: ['Use present tense for a near future plan.'],
		tags: ['question', 'planning'],
		phraseFamily: 'Asking follow-up questions',
		difficulty: 1,
		communicativeGoal: 'Ask about plans with a simple present-tense frame.',
		spokenCue: 'Ask it aloud before typing.',
		repairPrompts: ['Now ask: What are you doing tomorrow?'],
	},
	{
		id: 'family-repair-past-1',
		type: 'transform',
		sceneId: 'family-table',
		phase: 'repair',
		action: 'Tell a story',
		promptEnglish: 'Repair this idea: Yesterday I cooked, but I was tired.',
		targetItalian: 'Ieri ho cucinato, ma ero stanco.',
		acceptedItalian: [
			'ieri ho cucinato ma ero stanco',
			'ieri ho cucinato ma ero stanca',
		],
		hints: ['Use "ho cucinato" for the event and "ero" for the state.'],
		tags: ['past', 'imperfect'],
		phraseFamily: 'Telling past events',
		difficulty: 2,
		communicativeGoal: 'Separate event and background state in the past.',
		spokenCue: 'Say the whole sentence once without stopping.',
		repairPrompts: ['Now say: Yesterday I worked, but I was happy.'],
	},
	{
		id: 'bookshop-warm-taste',
		type: 'chunk',
		sceneId: 'bookshop',
		phase: 'warmup',
		action: 'Describe taste',
		promptEnglish: 'I like stories about...',
		targetItalian: 'Mi piacciono le storie su...',
		acceptedItalian: [
			'mi piacciono le storie su',
			'mi piacciono le storie sulle',
		],
		hints: ['Plural thing liked: "mi piacciono".'],
		tags: ['plural', 'chunk'],
		phraseFamily: 'Describing taste',
		difficulty: 2,
		communicativeGoal: 'Start a preference sentence quickly.',
		spokenCue: 'Say the frame, then add one topic aloud.',
		repairPrompts: ['Now say: I like stories about cities.'],
	},
	{
		id: 'bookshop-produce-compare-1',
		type: 'sentence',
		sceneId: 'bookshop',
		phase: 'produce',
		action: 'Compare',
		promptEnglish: 'I prefer short novels because I read slowly.',
		targetItalian: 'Preferisco i romanzi brevi perche leggo lentamente.',
		acceptedItalian: [
			'preferisco i romanzi brevi perche leggo lentamente',
			'preferisco i romanzi brevi perché leggo lentamente',
		],
		hints: ['"I prefer" is "Preferisco".'],
		tags: ['reason', 'culture'],
		phraseFamily: 'Comparing',
		difficulty: 2,
		communicativeGoal: 'Give a preference plus a reason.',
		spokenCue: 'Say it aloud once, then type the version you remember.',
		repairPrompts: ['Change the reason: because I do not have much time.'],
	},
	{
		id: 'news-warm-ho-letto',
		type: 'chunk',
		sceneId: 'piazza-newsstand',
		phase: 'warmup',
		action: 'Read headline',
		promptEnglish: 'I read that...',
		targetItalian: 'Ho letto che...',
		acceptedItalian: ['ho letto che'],
		hints: ['This opens a news or culture comment.'],
		tags: ['news', 'chunk'],
		phraseFamily: 'Summarising news',
		difficulty: 1,
		communicativeGoal: 'Start a simple news comment.',
		spokenCue: 'Say it aloud with today\'s headline in mind.',
		repairPrompts: ['Now say: I read that there is a concert.'],
	},
	{
		id: 'news-produce-view-1',
		type: 'sentence',
		sceneId: 'piazza-newsstand',
		phase: 'produce',
		action: 'Ask view',
		promptEnglish: 'What do you think about this news?',
		targetItalian: 'Che cosa pensi di questa notizia?',
		acceptedItalian: [
			'che cosa pensi di questa notizia',
			'cosa pensi di questa notizia',
			'che ne pensi di questa notizia',
		],
		hints: ['"News item" is "notizia".'],
		tags: ['question', 'news'],
		phraseFamily: 'Asking follow-up questions',
		difficulty: 2,
		communicativeGoal: 'Turn a topic into a social question.',
		spokenCue: 'Ask it aloud in one breath.',
		repairPrompts: ['Now ask: What do you think about this film?'],
	},
	{
		id: 'news-speak-soft-disagree',
		type: 'scene',
		sceneId: 'piazza-newsstand',
		phase: 'speak',
		action: 'Disagree softly',
		promptEnglish: 'Maybe, but I am not completely convinced.',
		targetItalian: 'Forse, ma non sono del tutto convinto.',
		acceptedItalian: [
			'forse ma non sono del tutto convinto',
			'forse ma non sono del tutto convinta',
		],
		hints: ['"Del tutto" means "completely".'],
		tags: ['softening', 'opinion'],
		phraseFamily: 'Softening',
		difficulty: 3,
		communicativeGoal: 'Disagree without sounding abrupt.',
		spokenCue: 'Say it gently before typing.',
		repairPrompts: ['Now say: Maybe, but I am not sure.'],
	},
	{
		id: 'station-warm-scusi',
		type: 'chunk',
		sceneId: 'station',
		phase: 'warmup',
		action: 'Repeat',
		promptEnglish: 'Sorry?',
		targetItalian: 'Scusi?',
		acceptedItalian: ['scusi', 'scusa'],
		hints: ['Use this before asking for repetition.'],
		tags: ['repair', 'politeness'],
		phraseFamily: 'Conversation repair',
		difficulty: 1,
		communicativeGoal: 'Interrupt politely instead of freezing.',
		spokenCue: 'Say it aloud immediately.',
		repairPrompts: ['Now add: Could you repeat?'],
	},
	{
		id: 'station-produce-solve-1',
		type: 'sentence',
		sceneId: 'station',
		phase: 'produce',
		action: 'Solve',
		promptEnglish: 'I do not understand which platform it is.',
		targetItalian: 'Non capisco qual e il binario.',
		acceptedItalian: [
			'non capisco qual e il binario',
			'non capisco qual è il binario',
			'non capisco quale e il binario',
		],
		hints: ['Use "Non capisco" to make the problem clear.'],
		tags: ['repair', 'question'],
		phraseFamily: 'Conversation repair',
		difficulty: 2,
		communicativeGoal: 'Name the misunderstanding clearly.',
		spokenCue: 'Say it aloud as a calm repair sentence.',
		repairPrompts: ['Now say: I do not understand the time.'],
	},
	{
		id: 'cinema-warm-mi-e-piaciuto',
		type: 'chunk',
		sceneId: 'cinema',
		phase: 'warmup',
		action: 'React',
		promptEnglish: 'I liked it.',
		targetItalian: 'Mi e piaciuto.',
		acceptedItalian: ['mi e piaciuto', 'mi è piaciuto'],
		hints: ['Useful after films, books, and events.'],
		tags: ['past', 'opinion'],
		phraseFamily: 'Reacting',
		difficulty: 2,
		communicativeGoal: 'React quickly after a shared experience.',
		spokenCue: 'Say it aloud, then add one reason if you can.',
		repairPrompts: ['Now say: I liked the book.'],
	},
	{
		id: 'cinema-produce-invite-1',
		type: 'sentence',
		sceneId: 'cinema',
		phase: 'produce',
		action: 'Invite',
		promptEnglish: 'Would you like to see a film this weekend?',
		targetItalian: 'Ti va di vedere un film questo fine settimana?',
		acceptedItalian: [
			'ti va di vedere un film questo fine settimana',
			'ti va di vedere un film nel fine settimana',
		],
		hints: ['"Ti va di..." is a natural invitation frame.'],
		tags: ['planning', 'question'],
		phraseFamily: 'Inviting',
		difficulty: 2,
		communicativeGoal: 'Make a low-pressure social invitation.',
		spokenCue: 'Say it aloud like an invitation, not a translation exercise.',
		repairPrompts: ['Now invite someone for a coffee.'],
	},
	{
		id: 'cinema-speak-reason-1',
		type: 'scene',
		sceneId: 'cinema',
		phase: 'speak',
		action: 'Explain why',
		promptEnglish: 'I liked it because the story was simple but moving.',
		targetItalian: 'Mi e piaciuto perche la storia era semplice ma commovente.',
		acceptedItalian: [
			'mi e piaciuto perche la storia era semplice ma commovente',
			'mi è piaciuto perché la storia era semplice ma commovente',
		],
		hints: ['Use "era" for a description in the past.'],
		tags: ['past', 'reason', 'opinion'],
		phraseFamily: 'Giving opinions',
		difficulty: 3,
		communicativeGoal: 'Give an opinion plus a reason after a film.',
		spokenCue: 'Say the idea aloud first. A rough version is welcome.',
		repairPrompts: ['Now say: I liked it because it was funny.'],
	},
	{
		id: 'core-question-dove-1',
		type: 'sentence',
		sceneId: 'family-table',
		phase: 'produce',
		action: 'Ask follow-up',
		promptEnglish: 'Where is your brother today?',
		targetItalian: 'Dove e tuo fratello oggi?',
		acceptedItalian: ['dove e tuo fratello oggi', 'dove è tuo fratello oggi'],
		hints: ['Use "tuo" before a singular family noun.'],
		tags: ['question', 'possessive', 'core'],
		phraseFamily: 'Asking follow-up questions',
		difficulty: 1,
		curriculumWeeks: [1, 4],
		roundFocus: 'core',
		strand: 'output',
		keyVerb: 'essere',
		construction: 'question:possessive',
	},
	{
		id: 'core-ci-sono-1',
		type: 'sentence',
		sceneId: 'family-table',
		phase: 'produce',
		action: 'Ask follow-up',
		promptEnglish: 'There are two people in the kitchen.',
		targetItalian: 'Ci sono due persone in cucina.',
		acceptedItalian: ['ci sono due persone in cucina'],
		hints: ['Use "ci sono" for "there are".'],
		tags: ['core', 'plural', 'place'],
		phraseFamily: 'Reliable everyday sentences',
		difficulty: 1,
		curriculumWeeks: [1, 4],
		roundFocus: 'core',
		strand: 'language-focus',
		keyVerb: 'essere',
		construction: 'ci-sono',
	},
	{
		id: 'core-fare-colazione-1',
		type: 'sentence',
		sceneId: 'milan-cafe',
		phase: 'produce',
		action: 'Greet',
		promptEnglish: 'Usually I have breakfast at home.',
		targetItalian: 'Di solito faccio colazione a casa.',
		acceptedItalian: ['di solito faccio colazione a casa'],
		hints: ['In Italian you "do" breakfast: "faccio colazione".'],
		tags: ['fare', 'routine', 'core'],
		phraseFamily: 'Reliable everyday sentences',
		difficulty: 1,
		curriculumWeeks: [1, 4],
		roundFocus: 'core',
		strand: 'fluency',
		keyVerb: 'fare',
		construction: 'fare-phrase',
	},
	{
		id: 'modal-posso-venire-1',
		type: 'chunk',
		sceneId: 'family-table',
		phase: 'warmup',
		action: 'Ask follow-up',
		promptEnglish: 'Can I come later?',
		targetItalian: 'Posso venire piu tardi?',
		acceptedItalian: [
			'posso venire piu tardi',
			'posso venire più tardi',
		],
		hints: ['Modal + infinitive: "posso venire".'],
		tags: ['modal', 'planning'],
		phraseFamily: 'Making plans',
		difficulty: 1,
		curriculumWeeks: [5, 8],
		roundFocus: 'verbs-frames',
		strand: 'fluency',
		keyVerb: 'potere',
		construction: 'modal-infinitive',
	},
	{
		id: 'modal-voglio-aiutare-1',
		type: 'sentence',
		sceneId: 'family-table',
		phase: 'produce',
		action: 'Offer help',
		promptEnglish: 'I want to help, but I have to leave soon.',
		targetItalian: 'Voglio aiutare, ma devo partire presto.',
		acceptedItalian: ['voglio aiutare ma devo partire presto'],
		hints: ['Two modals: "voglio" and "devo".'],
		tags: ['modal', 'family', 'planning'],
		phraseFamily: 'Offering help',
		difficulty: 2,
		curriculumWeeks: [5, 8],
		roundFocus: 'verbs-frames',
		strand: 'output',
		keyVerb: 'volere',
		construction: 'modal-chain',
	},
	{
		id: 'modal-negative-question-1',
		type: 'transform',
		sceneId: 'station',
		phase: 'repair',
		action: 'Confirm',
		promptEnglish: 'Can you not wait for me?',
		targetItalian: 'Non puoi aspettarmi?',
		acceptedItalian: ['non puoi aspettarmi', 'non puoi aspettare me'],
		hints: ['Put "non" before the modal.'],
		tags: ['modal', 'negative', 'question'],
		phraseFamily: 'Conversation repair',
		difficulty: 2,
		curriculumWeeks: [5, 8],
		roundFocus: 'verbs-frames',
		strand: 'language-focus',
		keyVerb: 'potere',
		construction: 'negative-modal-question',
	},
	{
		id: 'past-real-life-visit-1',
		type: 'sentence',
		sceneId: 'family-table',
		phase: 'produce',
		action: 'Tell a story',
		promptEnglish: 'Yesterday I saw Maria and we talked for an hour.',
		targetItalian: 'Ieri ho visto Maria e abbiamo parlato per un ora.',
		acceptedItalian: ['ieri ho visto maria e abbiamo parlato per un ora'],
		hints: ['Use "ho visto" and "abbiamo parlato".'],
		tags: ['past', 'family'],
		phraseFamily: 'Telling past events',
		difficulty: 2,
		curriculumWeeks: [9, 12],
		roundFocus: 'past-pronouns',
		strand: 'output',
		keyVerb: 'vedere',
		construction: 'passato-prossimo',
	},
	{
		id: 'past-pronoun-called-1',
		type: 'transform',
		sceneId: 'family-table',
		phase: 'repair',
		action: 'Tell a story',
		promptEnglish: 'I called him, but he did not answer me.',
		targetItalian: 'L ho chiamato, ma non mi ha risposto.',
		acceptedItalian: ['l ho chiamato ma non mi ha risposto'],
		hints: ['Keep the clear chunks: "l ho chiamato" and "mi ha risposto".'],
		tags: ['past', 'pronoun', 'clitic'],
		phraseFamily: 'Telling past events',
		difficulty: 3,
		curriculumWeeks: [9, 16],
		roundFocus: 'past-pronouns',
		strand: 'language-focus',
		keyVerb: 'chiamare',
		construction: 'past-direct-pronoun',
	},
	{
		id: 'pronoun-clear-gave-1',
		type: 'sentence',
		sceneId: 'family-table',
		phase: 'produce',
		action: 'Tell a story',
		promptEnglish: 'I gave it to Maria yesterday.',
		targetItalian: 'L ho dato a Maria ieri.',
		acceptedItalian: ['l ho dato a maria ieri'],
		hints: ['Use the clear form before compressed forms: "a Maria".'],
		tags: ['pronoun', 'past', 'indirect-object'],
		phraseFamily: 'Telling past events',
		difficulty: 3,
		curriculumWeeks: [13, 16],
		roundFocus: 'past-pronouns',
		strand: 'language-focus',
		keyVerb: 'dare',
		construction: 'clear-indirect-object',
	},
	{
		id: 'pronoun-told-her-1',
		type: 'sentence',
		sceneId: 'family-table',
		phase: 'produce',
		action: 'Tell a story',
		promptEnglish: 'I told her that I was tired.',
		targetItalian: 'Le ho detto che ero stanco.',
		acceptedItalian: [
			'le ho detto che ero stanco',
			'le ho detto che ero stanca',
		],
		hints: ['"Le ho detto" means "I told her".'],
		tags: ['pronoun', 'past', 'imperfect'],
		phraseFamily: 'Telling past events',
		difficulty: 3,
		curriculumWeeks: [13, 16],
		roundFocus: 'past-pronouns',
		strand: 'output',
		keyVerb: 'dire',
		construction: 'indirect-pronoun-dire',
	},
	{
		id: 'opinion-family-decision-1',
		type: 'scene',
		sceneId: 'family-table',
		phase: 'speak',
		action: 'Compare tastes',
		promptEnglish: 'In my opinion, we should decide together.',
		targetItalian: 'Secondo me, dobbiamo decidere insieme.',
		acceptedItalian: ['secondo me dobbiamo decidere insieme'],
		hints: ['Use "dobbiamo" for "we should / we have to".'],
		tags: ['opinion', 'modal', 'family'],
		phraseFamily: 'Giving opinions',
		difficulty: 2,
		curriculumWeeks: [17, 20],
		roundFocus: 'verbs-frames',
		strand: 'output',
		keyVerb: 'decidere',
		construction: 'opinion-modal',
	},
	{
		id: 'politics-simple-view-1',
		type: 'sentence',
		sceneId: 'piazza-newsstand',
		phase: 'produce',
		action: 'Ask view',
		promptEnglish: 'I do not know much, but I think the issue is important.',
		targetItalian: 'Non ne so molto, ma penso che il problema sia importante.',
		acceptedItalian: [
			'non ne so molto ma penso che il problema sia importante',
			'non ne so molto ma penso che il problema e importante',
		],
		hints: ['Use the chunk "non ne so molto" to soften the opinion.'],
		tags: ['politics', 'opinion', 'softening'],
		phraseFamily: 'Softening',
		difficulty: 3,
		curriculumWeeks: [17, 20],
		roundFocus: 'topics',
		strand: 'output',
		keyVerb: 'pensare',
		construction: 'soft-political-opinion',
	},
	{
		id: 'future-plan-family-1',
		type: 'sentence',
		sceneId: 'family-table',
		phase: 'produce',
		action: 'Ask follow-up',
		promptEnglish: 'Next week we will talk about it with the family.',
		targetItalian: 'La settimana prossima ne parleremo con la famiglia.',
		acceptedItalian: ['la settimana prossima ne parleremo con la famiglia'],
		hints: ['"Ne parleremo" means "we will talk about it".'],
		tags: ['future', 'pronoun', 'family'],
		phraseFamily: 'Making plans',
		difficulty: 3,
		curriculumWeeks: [17, 20],
		roundFocus: 'past-pronouns',
		strand: 'language-focus',
		keyVerb: 'parlare',
		construction: 'future-ne',
	},
	{
		id: 'connector-anche-se-1',
		type: 'sentence',
		sceneId: 'cinema',
		phase: 'produce',
		action: 'Explain why',
		promptEnglish: 'Even though I was tired, I wanted to go out.',
		targetItalian: 'Anche se ero stanco, volevo uscire.',
		acceptedItalian: [
			'anche se ero stanco volevo uscire',
			'anche se ero stanca volevo uscire',
		],
		hints: ['"Anche se" is a useful connector for longer turns.'],
		tags: ['connector', 'imperfect', 'stretch'],
		phraseFamily: 'Complex phrase fluency',
		difficulty: 3,
		curriculumWeeks: [21, 24],
		roundFocus: 'stretch',
		strand: 'fluency',
		keyVerb: 'volere',
		construction: 'anche-se',
	},
	{
		id: 'connector-dopo-aver-1',
		type: 'transform',
		sceneId: 'family-table',
		phase: 'repair',
		action: 'Tell a story',
		promptEnglish: 'After eating, we talked about the problem.',
		targetItalian: 'Dopo aver mangiato, abbiamo parlato del problema.',
		acceptedItalian: ['dopo aver mangiato abbiamo parlato del problema'],
		hints: ['Use "dopo aver" before the past participle.'],
		tags: ['connector', 'past', 'stretch'],
		phraseFamily: 'Complex phrase fluency',
		difficulty: 3,
		curriculumWeeks: [21, 24],
		roundFocus: 'stretch',
		strand: 'language-focus',
		keyVerb: 'parlare',
		construction: 'dopo-aver',
	},
	{
		id: 'conditional-light-1',
		type: 'chunk',
		sceneId: 'milan-cafe',
		phase: 'warmup',
		action: 'Continue chat',
		promptEnglish: 'I would like to say one thing.',
		targetItalian: 'Vorrei dire una cosa.',
		acceptedItalian: ['vorrei dire una cosa'],
		hints: ['Treat "vorrei" as a high-frequency chunk.'],
		tags: ['conditional', 'stretch'],
		phraseFamily: 'Complex phrase fluency',
		difficulty: 3,
		curriculumWeeks: [21, 24],
		roundFocus: 'stretch',
		strand: 'fluency',
		keyVerb: 'dire',
		construction: 'conditional-chunk',
	},
]

export const sceneVocabulary: SceneVocabulary[] = [
	{
		id: 'v-cafe-posto',
		sceneId: 'milan-cafe',
		italian: 'il posto',
		english: 'the place',
		partOfSpeech: 'noun',
	},
	{
		id: 'v-cafe-pensare',
		sceneId: 'milan-cafe',
		italian: 'pensare',
		english: 'to think',
		partOfSpeech: 'verb',
	},
	{
		id: 'v-cafe-secondo-me',
		sceneId: 'milan-cafe',
		italian: 'secondo me',
		english: 'in my opinion',
		partOfSpeech: 'chunk',
	},
	{
		id: 'v-cafe-qui',
		sceneId: 'milan-cafe',
		italian: 'qui',
		english: 'here',
		partOfSpeech: 'adverb',
	},
	{
		id: 'v-family-settimana',
		sceneId: 'family-table',
		italian: 'la settimana',
		english: 'the week',
		partOfSpeech: 'noun',
	},
	{
		id: 'v-family-aiutare',
		sceneId: 'family-table',
		italian: 'aiutare',
		english: 'to help',
		partOfSpeech: 'verb',
	},
	{
		id: 'v-family-cena',
		sceneId: 'family-table',
		italian: 'la cena',
		english: 'dinner',
		partOfSpeech: 'noun',
	},
	{
		id: 'v-family-ieri',
		sceneId: 'family-table',
		italian: 'ieri',
		english: 'yesterday',
		partOfSpeech: 'adverb',
	},
	{
		id: 'v-book-romanzo',
		sceneId: 'bookshop',
		italian: 'il romanzo',
		english: 'the novel',
		partOfSpeech: 'noun',
	},
	{
		id: 'v-book-consigliare',
		sceneId: 'bookshop',
		italian: 'consigliare',
		english: 'to recommend',
		partOfSpeech: 'verb',
	},
	{
		id: 'v-book-storie',
		sceneId: 'bookshop',
		italian: 'le storie',
		english: 'the stories',
		partOfSpeech: 'noun',
	},
	{
		id: 'v-news-mostra',
		sceneId: 'piazza-newsstand',
		italian: 'la mostra',
		english: 'the exhibition',
		partOfSpeech: 'noun',
	},
	{
		id: 'v-news-ho-letto',
		sceneId: 'piazza-newsstand',
		italian: 'ho letto che',
		english: 'I read that',
		partOfSpeech: 'chunk',
	},
	{
		id: 'v-news-ne-so',
		sceneId: 'piazza-newsstand',
		italian: 'ne so',
		english: 'I know about it',
		partOfSpeech: 'chunk',
	},
	{
		id: 'v-station-binario',
		sceneId: 'station',
		italian: 'il binario',
		english: 'the platform',
		partOfSpeech: 'noun',
	},
	{
		id: 'v-station-ripetere',
		sceneId: 'station',
		italian: 'ripetere',
		english: 'to repeat',
		partOfSpeech: 'verb',
	},
	{
		id: 'v-station-lentamente',
		sceneId: 'station',
		italian: 'lentamente',
		english: 'slowly',
		partOfSpeech: 'adverb',
	},
	{
		id: 'v-cinema-film',
		sceneId: 'cinema',
		italian: 'il film',
		english: 'the film',
		partOfSpeech: 'noun',
	},
	{
		id: 'v-cinema-lento',
		sceneId: 'cinema',
		italian: 'lento',
		english: 'slow',
		partOfSpeech: 'adjective',
	},
	{
		id: 'v-cinema-potremmo',
		sceneId: 'cinema',
		italian: 'potremmo',
		english: 'we could',
		partOfSpeech: 'verb',
	},
]

export function getScene(sceneId: string) {
	return scenes.find((scene) => scene.id === sceneId) ?? scenes[0]
}

export function getExercise(exerciseId: string) {
	return exercises.find((exercise) => exercise.id === exerciseId)
}

export function getExercisesForScene(sceneId: string) {
	return exercises.filter((exercise) => exercise.sceneId === sceneId)
}

export function getVocabularyForScene(sceneId: string) {
	return sceneVocabulary.filter((item) => item.sceneId === sceneId)
}

export function getExerciseAction(exercise: Exercise) {
	return exercise.action ?? actionByPhraseFamily[exercise.phraseFamily] ?? 'Produce'
}

export function getExercisePhase(exercise: Exercise): SprintPhase {
	if (exercise.phase) return exercise.phase
	if (exercise.type === 'chunk') return 'warmup'
	if (exercise.type === 'transform') return 'repair'
	if (exercise.type === 'scene') return 'speak'
	return 'produce'
}

export function getExerciseRepairPrompts(exercise: Exercise) {
	if (exercise.repairPrompts?.length) return exercise.repairPrompts
	return [
		exercise.promptEnglish,
		`Change one detail and say it again: ${exercise.promptEnglish}`,
	]
}

export function getExercisesForAction(sceneId: string, action: string) {
	return getExercisesForScene(sceneId).filter(
		(exercise) => getExerciseAction(exercise) === action
	)
}
